# Generated by Django 3.2.4 on 2021-06-30 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_articles_cluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200)),
                ('item_count', models.IntegerField(default=0)),
                ('item_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_count', models.IntegerField(default=0)),
                ('total_unit', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
        migrations.DeleteModel(
            name='Clusters',
        ),
        migrations.AddField(
            model_name='article',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.cluster'),
        ),
    ]
