# Generated by Django 3.2.4 on 2021-06-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210630_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='item',
            new_name='cluster',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='model_name',
            new_name='headline',
        ),
        migrations.RemoveField(
            model_name='article',
            name='item_count',
        ),
        migrations.RemoveField(
            model_name='article',
            name='item_price',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='item_name',
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='cluster',
            name='cluster_no',
            field=models.IntegerField(default=0),
        ),
    ]
