# Generated by Django 3.2.4 on 2021-07-01 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210701_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.cluster', unique=True),
        ),
        migrations.AlterField(
            model_name='particle',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.pcluster', unique=True),
        ),
    ]
