# Generated by Django 3.2.4 on 2021-07-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_article_article_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_id',
            field=models.IntegerField(default=0),
        ),
    ]
