# Generated by Django 3.2.4 on 2021-07-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_remove_article_article_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='total_unit',
        ),
        migrations.AddField(
            model_name='cluster',
            name='news_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
