# Generated by Django 3.2.4 on 2021-07-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20210705_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcluster',
            name='total_unit',
        ),
        migrations.AddField(
            model_name='pcluster',
            name='news_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
